In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[[ 'charges',]]

In [10]:
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [12]:
scy=StandardScaler()
dependent=scy.fit_transform(dependent)

In [13]:
from sklearn.model_selection import GridSearchCV 
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','friedman_mse','poisson','absolute_error'],
              'max_features': ['sqrt','log2'],
              'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


C:\sabeen\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
20 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\sabeen\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\sabeen\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sabeen\anaconda3\Lib\site-packages\sklearn\tree\_classes.py", line 1377, in fit
    super()._fit(
  File "C:\sabeen\anacond

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'poisson', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [14]:
re=grid.cv_results_
print("TheR_score valueforbestparameter{}:".format(grid.best_params_))



TheR_score valueforbestparameter{'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'}:


In [15]:
table=pd.DataFrame.from_dict(re)
table


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.003936      0.001523         0.001531        0.002289   
1        0.002055      0.001549         0.000453        0.000560   
2        0.002774      0.001784         0.001588        0.001205   
3        0.001499      0.001762         0.000619        0.000970   
4        0.003933      0.001946         0.001143        0.000790   
5        0.003791      0.001026         0.001367        0.001133   
6        0.003108      0.000418         0.000526        0.001051   
7        0.003233      0.001906         0.000402        0.000803   
8        0.000801      0.001602         0.000000        0.000000   
9        0.000519      0.000719         0.000000        0.000000   
10       0.001554      0.001903         0.000000        0.000000   
11       0.000172      0.000345         0.000000        0.000000   
12       0.018735      0.005228         0.000000        0.000000   
13       0.015666      0.004494         0.002082        0.003682   
14       0.016318      0.005102         0.001669        0.003337   
15       0.008837      0.005895         0.002017        0.003993   

   param_criterion param_max_features param_splitter  \
0    squared_error               sqrt           best   
1    squared_error               sqrt         random   
2    squared_error               log2           best   
3    squared_error               log2         random   
4     friedman_mse               sqrt           best   
5     friedman_mse               sqrt         random   
6     friedman_mse               log2           best   
7     friedman_mse               log2         random   
8          poisson               sqrt           best   
9          poisson               sqrt         random   
10         poisson               log2           best   
11         poisson               log2         random   
12  absolute_error               sqrt           best   
13  absolute_error               sqrt         random   
14  absolute_error               log2           best   
15  absolute_error               log2         random   

                                               params  split0_test_score  \
0   {'criterion': 'squared_error', 'max_features':...           0.686037   
1   {'criterion': 'squared_error', 'max_features':...           0.661832   
2   {'criterion': 'squared_error', 'max_features':...           0.713457   
3   {'criterion': 'squared_error', 'max_features':...           0.720322   
4   {'criterion': 'friedman_mse', 'max_features': ...           0.753295   
5   {'criterion': 'friedman_mse', 'max_features': ...           0.635459   
6   {'criterion': 'friedman_mse', 'max_features': ...           0.689357   
7   {'criterion': 'friedman_mse', 'max_features': ...           0.595348   
8   {'criterion': 'poisson', 'max_features': 'sqrt...                NaN   
9   {'criterion': 'poisson', 'max_features': 'sqrt...                NaN   
10  {'criterion': 'poisson', 'max_features': 'log2...                NaN   
11  {'criterion': 'poisson', 'max_features': 'log2...                NaN   
12  {'criterion': 'absolute_error', 'max_features'...           0.699676   
13  {'criterion': 'absolute_error', 'max_features'...           0.658882   
14  {'criterion': 'absolute_error', 'max_features'...           0.624332   
15  {'criterion': 'absolute_error', 'max_features'...           0.700067   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.646167           0.758685           0.736274   
1            0.598883           0.646672           0.738894   
2            0.608711           0.736212           0.715245   
3            0.591647           0.631215           0.654858   
4            0.578120           0.722620           0.678587   
5            0.515874           0.724181           0.698207   
6            0.583368           0.711653           0.721674   
7            0.587802           0.593532           0.691512   
8                 NaN             

In [16]:
y_predt=grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(dependent,y_predt)
r_score

0.998667156135576

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:")) 
children_input=float(input("Children:")) 
sex_male_input=int(input("Sex Male 0 or 1:")) 
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))


Age: 28
BMI: 29
Children: 3
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [26]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))


Future_Prediction=[2.99923879]


In [27]:
import pickle  
filename="finalized_model_Tree.sav"

In [28]:
pickle.dump(grid,open(filename,'wb'))

In [29]:
preinput=sc.transform([[25,23,0,1,0]])
preinput

C:\sabeen\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.01155712, -1.25713795, -0.90861367,  0.98959079, -0.5074631 ]])

In [30]:
loaded_model=pickle.load(open("finalized_model_Forest.sav",'rb'))
result=loaded_model.predict(preinput)

C:\sabeen\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


In [31]:
result

array([1694.7964])

In [32]:
preoutput=scy.inverse_transform([result])

In [33]:
preoutput

array([[20529602.77910105]])